import { describe, expect, test } from "bun:test"
import { computeLaneChain } from "../src/lane-policy"
import { loadManifest } from "../src/state"
import { baseScoreFromCapabilityIndex, loadBundledCapability } from "../src/capability"
import { baseScore } from "../src/model-ranks"
import { BILLING_API_BOOST } from "../src/scoring"
import { defaultBillingOf } from "../src/provider-config"

// [2026-09-04]-[English localization: translate comments; no test-logic change]
// [2026-08-31]-[de-vendorization: DS last-seat reservation / pool-name ordering removed — api billing and unknown groups
//  sink via billingBoost×unknownPenalty; fixtures gained a provider field + generation-time same-source resolvers
//  (factory billing + capability-level global = unknown group)]
const shells = [
  { name: "cp-high", modelId: "cp", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 2 },
  { name: "cp-high-ro", modelId: "cp", provider: "github-copilot", pool: "copilot", effort: "high", capability: "ro", vision: false, cost: 2 },
  { name: "glm-high", modelId: "glm", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "rw", vision: false, cost: 1 },
  { name: "glm-high-ro", modelId: "glm", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "ro", vision: false, cost: 1 },
  { name: "ds-high", modelId: "ds", provider: "deepseek", pool: "deepseek", effort: "high", capability: "rw", vision: false, cost: 0 },
  { name: "ds-high-ro", modelId: "ds", provider: "deepseek", pool: "deepseek", effort: "high", capability: "ro", vision: false, cost: 0 },
  { name: "cp-medium", modelId: "cp-medium", provider: "github-copilot", pool: "copilot", effort: "medium", capability: "rw", vision: false },
  { name: "vision-high", modelId: "vision", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "rw", vision: true },
  { name: "review-glm-rw", modelId: "review", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "rw", vision: false },
  { name: "review-glm-ro", modelId: "review", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "ro", vision: false },
  { name: "review-cp-rw", modelId: "review-cp", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false },
  { name: "review-cp-ro", modelId: "review-cp", provider: "github-copilot", pool: "copilot", effort: "high", capability: "ro", vision: false },
] as const
const capability = (model: string) => ({ cp: 1, glm: 1, ds: 1, "cp-medium": 1, vision: 1, review: 1, "review-cp": 1 }[model] ?? 0)
const resolvers = { billingBoostOf: (provider: string) => defaultBillingOf(provider) === "subscription" ? 1.0 : BILLING_API_BOOST }

describe("candidate-chain algorithm", () => {
  test("[final-review P0-1] tier grouping primary key: S/api(0.85) does not sink below A/subscription(0.85) (same affinity, same product)", () => {
    const mix = [
      { name: "s-api", modelId: "s-api", provider: "deepseek", pool: "deepseek", effort: "high", capability: "rw", vision: false, cost: 9 },
      { name: "a-sub", modelId: "a-sub", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 0 },
    ]
    const cap = (id: string) => (id === "s-api" ? { score: 1.0, tier: "S" as const } : { score: 0.85, tier: "A" as const })
    // When main has no same-level B, fall back to the adjacent A first; S is only the farther backup.
    expect(computeLaneChain(mix, cap, "main", resolvers)).toEqual(["a-sub", "s-api"])
    // Unknown group (0.75) only sinks within the same tier: B-unknown still leads C-known (the tier primary key is irreversible)
    const tierMix = [
      { name: "b-unknown", modelId: "b-unknown", provider: "my-gateway", pool: "zen", effort: "high", capability: "rw", vision: false },
      { name: "c-known", modelId: "c-known", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false },
    ]
    const cap2 = (id: string) => (id === "b-unknown" ? { score: 0.7, tier: "B" as const } : { score: 0.55, tier: "C" as const })
    // A known C model can fill in across levels as main's adjacent lower level.
    expect(computeLaneChain(tierMix, cap2, "main", { unknownOf: (id) => id === "b-unknown" })).toEqual(["b-unknown", "c-known"])
  })
  test("all six lanes generated by capability × affinity × structural gate × billing factor; api billing factor sinks to bottom (no reserved seat)", () => {
    // economy/mechanical/main: same-score subscription shells edge out api-billed ds — the D3 last-seat reservation is abolished, pure factor sinking
    expect(computeLaneChain(shells, capability, "economy", resolvers)).toEqual(["cp-medium", "glm-high", "cp-high", "review-cp-rw"])
    expect(computeLaneChain(shells, capability, "mechanical", resolvers)).toEqual(["cp-medium", "glm-high", "cp-high", "review-cp-rw"])
    // main defaults to the medium effort (2026-09-02 thinking-level preference layer): with equal capability, the medium ordinal precedes high
    expect(computeLaneChain(shells, capability, "main", resolvers)).toEqual(["cp-medium", "glm-high", "cp-high", "review-cp-rw"])
    expect(computeLaneChain(shells, capability, "hard", resolvers)).toEqual(["glm-high", "cp-high", "review-cp-rw", "review-glm-rw"])
    expect(computeLaneChain(shells, capability, "vision", resolvers)).toEqual(["vision-high"])
    expect(computeLaneChain(shells, capability, "review", resolvers)).toEqual(["glm-high-ro", "cp-high-ro", "review-cp-ro", "review-glm-ro"])
    // Two-shell scenario: ds stays in the chain (with no competitors, factor sinking does not eliminate)
    expect(computeLaneChain([shells[0], shells[4]], capability, "main", resolvers)).toEqual(["cp-high", "ds-high"])
  })
  test("no billing bias without injected resolvers (pure capability × affinity × cost adjudication); an explicit subscription mark can reverse the api sink", () => {
    // No resolvers: ds cost 0 → on equal scores the cost tiebreak puts it first (no pool-name rules)
    expect(computeLaneChain(shells, capability, "economy")).toEqual(["cp-medium", "ds-high", "glm-high", "cp-high"])
    // Explicitly marking deepseek as subscription (1.0) stops the sinking, restoring the cost tiebreak order
    const flat = { billingBoostOf: () => 1.0 }
    expect(computeLaneChain(shells, capability, "economy", flat)).toEqual(["cp-medium", "ds-high", "glm-high", "cp-high"])
    expect(computeLaneChain([
      { name: "a", modelId: "a", pool: "glm", effort: "high", capability: "rw", vision: false, cost: 2 },
      { name: "b", modelId: "b", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 1 },
      { name: "c", modelId: "c", pool: "copilot", effort: "low", capability: "rw", vision: false },
    ], (id) => id === "c" ? 0.85 : 1, "main")).toEqual(["b", "a", "c"])
  })
  test("unknown-group penalty: global-fallback models rank after known ones at equal score (unknownOf resolver)", () => {
    const mix = [
      { name: "known", modelId: "glm", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "rw", vision: false },
      { name: "mystery", modelId: "mystery", provider: "my-gateway", pool: "zen", effort: "high", capability: "rw", vision: false },
    ]
    expect(computeLaneChain(mix, () => 1, "main", { unknownOf: (id) => id === "mystery" })).toEqual(["known", "mystery"])
    expect(computeLaneChain(mix, () => 1, "main")).toEqual(["known", "mystery"]) // equal scores fall back to name order, consistent
  })
  test("capability pools: mechanical/main/hard require C/B/A respectively; top two models of the tier below fill upward", () => {
    const levels = [
      { name: "c", modelId: "c", pool: "glm", effort: "high", capability: "rw", vision: false },
      { name: "b", modelId: "b", pool: "glm", effort: "high", capability: "rw", vision: false },
      { name: "a", modelId: "a", pool: "glm", effort: "high", capability: "ro", vision: false },
      { name: "s", modelId: "s", pool: "glm", effort: "high", capability: "ro", vision: false },
    ]
    const cap = (id: string) => ({ c: { score: 0.55, tier: "C" as const }, b: { score: 0.7, tier: "B" as const }, a: { score: 0.85, tier: "A" as const }, s: { score: 1, tier: "S" as const } }[id]!)
    expect(computeLaneChain([levels[0]], cap, "mechanical")).toEqual(["c"])
    expect(computeLaneChain(levels.slice(0, 2), cap, "main")).toEqual(["b", "c"])
    // [2026-09-02]-[ro/rw pool split: hard picks only from the rw pool (b; a/s in this fixture are ro, own pool non-empty so no cross-pool); review locks the ro pool]
    expect(computeLaneChain(levels.slice(1, 3), cap, "hard")).toEqual(["b"])
    expect(computeLaneChain(levels.slice(2), cap, "review")).toEqual(["s", "a"])
  })
  test("ro/rw pool split: review locks ro faces, non-review locks rw faces; cross-pool fallback only when the own pool is empty", () => {
    const mrw = { name: "mrw", modelId: "m", pool: "glm", effort: "high", capability: "rw", vision: false }
    const mro = { name: "mro", modelId: "m", pool: "glm", effort: "high", capability: "ro", vision: false }
    const nro = { name: "nro", modelId: "n", pool: "glm", effort: "high", capability: "ro", vision: false }
    const cap = () => ({ score: 1, tier: "S" as const })
    expect(computeLaneChain([mrw, mro, nro], cap, "hard")).toEqual(["mrw"])
    expect(computeLaneChain([mro, nro], cap, "hard")).toEqual(["mro", "nro"])
    expect(computeLaneChain([mrw], cap, "review")).toEqual(["mrw"])
    expect(computeLaneChain([mrw, mro, nro], cap, "review")).toEqual(["mro", "nro"])
  })
  test("[2026-09-05] review last-resort seats: only B-tier ro candidates (no S primary / A fallback) → chain stays non-empty and takes the best ro shells; non-review lanes keep the empty-chain terminal semantics", () => {
    const bRo = [
      { name: "b1-ro", modelId: "b1", pool: "glm", effort: "high", capability: "ro", vision: false },
      { name: "b2-ro", modelId: "b2", pool: "glm", effort: "medium", capability: "ro", vision: false },
      { name: "b3-ro", modelId: "b3", pool: "glm", effort: "high", capability: "ro", vision: false },
    ]
    const capB = () => ({ score: 0.7, tier: "B" as const })
    // review: L5 primary / L4 fallback both empty → top-2 of the tier/score-ordered pool (high effort beats medium)
    expect(computeLaneChain(bRo, capB, "review")).toEqual(["b1-ro", "b3-ro"])
    // hard (L4) with only a C(L2) candidate: no primary, no adjacent fallback → chain stays empty (terminal failure protocol unchanged)
    const cRo = [{ name: "c-ro", modelId: "c1", pool: "glm", effort: "high", capability: "ro", vision: false }]
    const capC = () => ({ score: 0.55, tier: "C" as const })
    expect(computeLaneChain(cRo, capC, "hard")).toEqual([])
  })
  test("same-level first: economy with an L1 available keeps stronger models out of the candidate chain", () => {    const levels = ["l1", "l2", "l5"].map((id) => ({ name: id, modelId: id, pool: "glm", effort: "low", capability: "rw", vision: false }))
    const cap = (id: string) => ({
      l1: { score: 0.55, tier: "C" as const, source: "global" },
      l2: { score: 0.55, tier: "C" as const, source: "exact" },
      l5: { score: 1, tier: "S" as const, source: "exact" },
    }[id]!)
    expect(computeLaneChain(levels, cap, "economy")).toEqual(["l1", "l2", "l5"])
  })
  test("economy without L1 falls back to the nearest level, never skipping L2 straight to L5", () => {
    const levels = ["l2", "l3", "l5"].map((id) => ({ name: id, modelId: id, pool: "glm", effort: "low", capability: "rw", vision: false }))
    const cap = (id: string) => ({
      l2: { score: 0.55, tier: "C" as const, source: "exact" },
      l3: { score: 0.7, tier: "B" as const, source: "exact" },
      l5: { score: 1, tier: "S" as const, source: "exact" },
    }[id]!)
    expect(computeLaneChain(levels, cap, "economy")).toEqual(["l2", "l3"])
  })
  test("fallback does not crowd out same-level redundancy: main keeps four B-level candidates before appending two cross-level fallbacks", () => {
    const six = ["b1", "b2", "b3", "b4", "c1", "c2"].map((id) => ({ name: id, modelId: id, pool: "glm", effort: "high", capability: "rw", vision: false }))
    const cap = (id: string) => id.startsWith("b") ? { score: 0.7, tier: "B" as const } : { score: 0.55, tier: "C" as const }
    expect(computeLaneChain(six, cap, "main")).toEqual(["b1", "b2", "b3", "b4", "c1", "c2"])
  })
  test("thinking-effort partition: off shell = lane-level fallback, does not take the chain head when the lane has thinking candidates", () => {
    // hard: S model has only off, A model has high — thinking efforts lead as a group; the off partition runs its own same-level/fallback ordering and sinks last
    const mix = [
      { name: "s-off", modelId: "s-off", pool: "glm", effort: "off", capability: "rw", vision: false },
      { name: "a-high", modelId: "a-high", pool: "glm", effort: "high", capability: "rw", vision: false },
      { name: "a-off", modelId: "a-off", pool: "glm", effort: "off", capability: "rw", vision: false },
    ]
    const cap = (id: string) => ({ "s-off": { score: 1, tier: "S" as const }, "a-high": { score: 0.85, tier: "A" as const }, "a-off": { score: 0.85, tier: "A" as const } }[id]!)
    expect(computeLaneChain(mix, cap, "hard")).toEqual(["a-high", "a-off", "s-off"])
  })
  test("thinking-effort partition: all-off candidates still form a chain (on/off-only models fall back without stalling)", () => {
    const offs = ["o1", "o2"].map((id) => ({ name: id, modelId: id, pool: "glm", effort: "off", capability: "rw", vision: false }))
    const cap = (id: string) => ({ o1: { score: 0.7, tier: "B" as const }, o2: { score: 0.55, tier: "C" as const } }[id]!)
    expect(computeLaneChain(offs, cap, "mechanical")).toEqual(["o2", "o1"])
  })
  test("thinking-effort partition: with multiple efforts per model the thinking shell represents the model (off no longer displaces its own model's thinking shell)", () => {
    const mix = [
      { name: "m-off", modelId: "m", pool: "glm", effort: "off", capability: "rw", vision: false },
      { name: "m-medium", modelId: "m", pool: "glm", effort: "medium", capability: "rw", vision: false },
      { name: "m-off-ro", modelId: "m", pool: "glm", effort: "off", capability: "ro", vision: false },
    ]
    expect(computeLaneChain(mix, () => ({ score: 0.7, tier: "B" as const }), "main")).toEqual(["m-medium"])
  })
  test("favorites first: favorited models rank ahead within the same tier (over product score/lexicographic order; no inversion across tiers)", () => {
    const sameTier = [
      { name: "x-high", modelId: "x", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 1 },
      { name: "y-high", modelId: "y", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 1 },
    ]
    const cap = () => ({ score: 1, tier: "S" as const })
    // No preference: equal score + equal affinity falls back to name order
    expect(computeLaneChain(sameTier, cap, "main", resolvers)).toEqual(["x-high", "y-high"])
    // Favorite y: overtakes within the same tier (explicit user intent)
    expect(computeLaneChain(sameTier, cap, "main", resolvers, new Set(["y"]))).toEqual(["y-high", "x-high"])
    // [2026-09-02 vision penalty removed]-a vision model ties with plain-text shells in a text lane (vision only does
    // vision-pool filtering): equal score + equal affinity falls back to name order; favoriting a vision model makes it
    // overtake (explicit user intent)
    const visionMix = [
      { name: "plain-high", modelId: "plain", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "rw", vision: false, cost: 1 },
      { name: "vis-high", modelId: "vis", provider: "zhipuai-coding-plan", pool: "glm", effort: "high", capability: "rw", vision: true, cost: 1 },
    ]
    expect(computeLaneChain(visionMix, cap, "main", resolvers)).toEqual(["plain-high", "vis-high"])
    expect(computeLaneChain(visionMix, cap, "main", resolvers, new Set(["vis"]))).toEqual(["vis-high", "plain-high"])
    // No inversion across levels: hard's same-level (A) candidate beats a favorited cross-level S fallback (favorites apply only within the same level / same distance)
    const tiers = [
      { name: "s-high", modelId: "s", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 1 },
      { name: "a-high", modelId: "a", provider: "github-copilot", pool: "copilot", effort: "high", capability: "rw", vision: false, cost: 1 },
    ]
    const cap2 = (id: string) => (id === "s" ? { score: 1, tier: "S" as const } : { score: 0.85, tier: "A" as const })
    expect(computeLaneChain(tiers, cap2, "hard", resolvers, new Set(["s"]))).toEqual(["a-high", "s-high"])
  })
  test("generated manifest's six chains share one source with the bundled capability snapshot (incl. billing/unknown-group factors and tier grouping); referenced shells exist and review includes a GLM ro shell", () => {
    const manifest = loadManifest(); const bundled = loadBundledCapability()
    // Same-source resolvers as gen-shells: capabilityOf returns {score,tier} (tier grouping primary key shares one source)
    const cap = (modelId: string) => baseScoreFromCapabilityIndex(modelId, bundled) ?? baseScore(modelId)
    const genResolvers = {
      billingBoostOf: (provider: string) => defaultBillingOf(provider) === "subscription" ? 1.0 : BILLING_API_BOOST,
      unknownOf: (modelId: string) => (baseScoreFromCapabilityIndex(modelId, bundled)?.source ?? baseScore(modelId).source) === "global",
    }
    for (const lane of ["economy", "mechanical", "main", "hard", "vision", "review"] as const) {
      const expected = computeLaneChain(manifest.shells, cap, lane, genResolvers)
      expect(manifest.lanes[lane]).toEqual(expected)
      expect(manifest.lanes[lane].every((name) => manifest.shells.some((shell) => shell.name === name))).toBe(true)
    }
    for (const lane of ["economy", "mechanical", "main", "hard", "vision"] as const) expect(computeLaneChain(shells, capability, lane, resolvers).every((name) => !name.endsWith("-ro"))).toBe(true)
    expect(computeLaneChain(shells, capability, "review", resolvers).every((name) => name.endsWith("-ro"))).toBe(true)
    expect(computeLaneChain(shells, capability, "review", resolvers)).toContain("glm-high-ro")
    for (const lane of ["economy", "mechanical", "main", "hard", "vision", "review"] as const) {
      const chain = computeLaneChain(shells, capability, lane, resolvers)
      expect(new Set(chain.map((name) => shells.find((shell) => shell.name === name)!.modelId)).size).toBeLessThanOrEqual(4)
      // api billing sinks: with equal capability and affinity, deepseek shells rank after subscription shells (factor 0.85, no reserved seat)
      const ds = chain.findIndex((name) => shells.find((shell) => shell.name === name)!.pool === "deepseek")
      expect(ds < 0 || ds === chain.length - 1).toBe(true)
    }
    expect(manifest.lanes.review.every((name) => manifest.shells.find((shell) => shell.name === name)!.capability === "ro")).toBe(true)
  })
})
