// [2026-09-04]-[English localization: translate comments and status messages; no logic change]
// Dynamic capability grading (v1.4): third-party authoritative indices -> capability.json (TTL 24h) -> api override layer for baseScore
// [2026-08-31]-[curated table upgraded to dynamic grading: primary source Artificial Analysis Data API v2
//  (GET /api/v2/data/llms/models, x-api-key; indices such as evaluations.artificial_analysis_intelligence_index,
//   tolerating short fields intelligence_index/coding_index/agentic_index), backup source OpenRouter
//  (GET /api/v1/models?sort=coding-high-to-low, public; intelligence/coding/agentic);
//  LMArena (api.wulong.dev ELO) is optional cross-validation only (log-only, does not affect scoring)]-
// [fail-open iron rule: on fetch failure/offline/429 keep last-good or fall back to the model-ranks curated table, never block delegation;
//  matching: api exact -> api longest prefix (>=4 chars to avoid false hits) -> curated exact/prefix/family/global fallback level by level]
// [scoring chain unchanged: total=base*effortFit*health*water*costBias*peak, only the base source is switchable;
//  tier still uses TIER_SCORE mapping (S=1.0/A=0.85/B=0.7/C=0.55), comparable with the curated calibration, tier group order unchanged]
import { CAPABILITY_TTL, paths, readJson, writeJsonAtomic, appendStatusLog } from "./state"
import { baseScore, TIER_SCORE, type Tier } from "./model-ranks"
import bundledDefaultJson from "./capability-default.json"
import { loadCapabilityRank } from "./user-overrides"
import type { CapabilityOptions } from "./types"

export type CapabilitySourceName = "artificial-analysis" | "openrouter"

export interface CapabilityEntry {
  score: number // index priority intelligence > coding > agentic (0-100 scale)
  intelligence?: number | null
  coding?: number | null
  agentic?: number | null
}

export interface CapabilityThresholds { S: number; A: number; B: number }

export interface CapabilityIndex {
  source: CapabilitySourceName
  version: string | null // for decision-log traceability (etag / data version / derived date)
  fetched_at: number // epoch seconds
  thresholds: CapabilityThresholds
  models: Record<string, CapabilityEntry> // key=normalizeModelKey(name)
  /** index=real index (absolute threshold scale); rank=derived from rank position (quantile scale) */
  score_kind?: "index" | "rank"
  /** [2026-08-31]-[bundled default rank snapshot marker (generated by gen:capability; fallback for offline/fetch failure, iterated manually per release)] */
  bundled?: boolean
  counts?: { models: number }
}

// [2026-09-03]-[manual capability rank override layer: capability-rank.json (user config, order=capability descending) overrides
//  live api/bundled snapshot -- on hit return the manual result, on miss go through the original three-level fallback chain;
//  score=linear rank percentile (first place 100 linearly down to last place 0, same semantics as the OpenRouter rank order),
//  thresholds quantile (p80/p60/p40, same refreshCapability rank calibration: top20% S / next20% A / next20% B / rest C)]
export type BaseSourceKind = "api" | "bundled" | "exact" | "prefix" | "family" | "global" | "manual"

export interface DynamicBaseResult {
  score: number
  /** Raw capability index: only used for fine-grained ordering within the same tier, avoiding tier discretization flattening real differences. */
  rawScore?: number
  tier: Tier
  source: BaseSourceKind
  version: string | null // non-null on api/bundled hit (capability.json live version / bundled-xx snapshot version)
  matchedAs?: string // third-party model name hit by api/bundled (normalized)
}

const DEFAULT_THRESHOLDS: CapabilityThresholds = { S: 62, A: 55, B: 45 }
const FETCH_TIMEOUT_MS = 20_000
const AA_BASE = "https://artificialanalysis.ai/api/v2"
const OR_BASE = "https://openrouter.ai/api/v1"
const LMARENA_URL = "https://api.wulong.dev/api/v1/leaderboard"
const MIN_PREFIX_LEN = 4

// ---- pure function layer ----

/** Model key normalization: lowercase -> strip provider prefix -> strip "(High)"/"[04-14]" variant segments -> fold illegal chars into "-" */
export function normalizeModelKey(name: string): string {
  let s = String(name ?? "").toLowerCase().trim()
  if (s.includes("/")) s = s.slice(s.lastIndexOf("/") + 1)
  s = s.replace(/\([^)]*\)/g, " ").replace(/\[[^\]]*\]/g, " ")
  s = s.replace(/[^a-z0-9.]+/g, "-")
  return s.replace(/-+/g, "-").replace(/^[-.]+|[-.]+$/g, "")
}

function num(v: unknown): number | null {
  return typeof v === "number" && Number.isFinite(v) ? v : null
}

/** Index -> tier (S/A/B/C; score >= threshold takes the higher tier) */
export function tierOfScore(score: number, th: CapabilityThresholds): Tier {
  if (score >= th.S) return "S"
  if (score >= th.A) return "A"
  if (score >= th.B) return "B"
  return "C"
}

/** Ascending quantile (linear rounded index; returns null for empty scores) */
export function percentileOf(sortedAsc: number[], p: number): number | null {
  if (sortedAsc.length === 0) return null
  const idx = Math.min(sortedAsc.length - 1, Math.max(0, Math.floor(p * (sortedAsc.length - 1))))
  return sortedAsc[idx]!
}

/** Threshold resolution: absolute thresholds (default 62/55/45, must satisfy S>A>B) or "quantile" (p80/p60/p40) */
export function resolveThresholds(
  spec: CapabilityOptions["tierThresholds"],
  scores: number[],
): CapabilityThresholds {
  if (spec === "quantile") {
    const asc = [...scores].sort((a, b) => a - b)
    const s80 = percentileOf(asc, 0.8) ?? DEFAULT_THRESHOLDS.S
    const s60 = percentileOf(asc, 0.6) ?? DEFAULT_THRESHOLDS.A
    const s40 = percentileOf(asc, 0.4) ?? DEFAULT_THRESHOLDS.B
    return s80 > s60 && s60 > s40 ? { S: s80, A: s60, B: s40 } : DEFAULT_THRESHOLDS
  }
  const t = {
    S: num(spec?.S) ?? DEFAULT_THRESHOLDS.S,
    A: num(spec?.A) ?? DEFAULT_THRESHOLDS.A,
    B: num(spec?.B) ?? DEFAULT_THRESHOLDS.B,
  }
  return t.S > t.A && t.A > t.B ? t : DEFAULT_THRESHOLDS
}

function firstIndex(...vals: Array<number | null | undefined>): number | null {
  for (const v of vals) if (typeof v === "number") return v
  return null
}

export interface ParsedSource {
  models: Record<string, CapabilityEntry>
  versionHint: string | null
  /** index=real index fields (AA is always index); rank=percentile derived from sort order (fallback when the OR public source has no index fields) */
  scoreKind: "index" | "rank"
}

/** AA v2 response parsing (data[]; evaluations long/short field compatibility; name/slug/id three-level naming) */
export function parseAaModels(json: unknown): ParsedSource {
  const arr = Array.isArray((json as any)?.data) ? (json as any).data : Array.isArray(json) ? json : []
  const models: Record<string, CapabilityEntry> = {}
  let versionHint: string | null = null
  for (const m of arr) {
    const rawName = String(m?.name ?? m?.slug ?? m?.id ?? "")
    const ev = m?.evaluations ?? m ?? {}
    const intelligence = firstIndex(
      num(ev.artificial_analysis_intelligence_index), num(ev.intelligence_index),
    )
    const coding = firstIndex(
      num(ev.artificial_analysis_coding_index), num(ev.coding_index),
    )
    const agentic = firstIndex(
      num(ev.artificial_analysis_agentic_index), num(ev.agentic_index),
    )
    const score = firstIndex(intelligence, coding, agentic)
    const key = normalizeModelKey(rawName)
    if (!key || score === null) continue
    models[key] = { score, intelligence, coding, agentic }
    const rel = String(m?.release_date ?? m?.last_updated ?? m?.updated_at ?? "")
    if (rel && rel > (versionHint ?? "")) versionHint = rel
  }
  return { models, versionHint, scoreKind: "index" }
}

/**
 * OpenRouter /models response parsing (data[]; id="vendor/model" strips the provider).
 * [2026-08-31]-[public source measured to lack top-level intelligence/coding/agentic fields: if present use real indices (scoreKind=index);
 *  otherwise derive percentile scores from the sort=coding-high-to-low order (first place 100 linearly down to last place 0, scoreKind=rank,
 *  threshold layer forces the quantile mapping -- the order is the coding order, a quantile mapping path allowed by the spec)]
 * [2026-09-02 fix]-[official indices actually live in benchmarks.artificial_analysis (AA-republished intelligence/coding/agentic_index,
 *  measured 179/421 models have data): previously only reading top-level fields misjudged "no index" -> the whole table fell into rank mode;
 *  rank mode linearly mapped models "without evaluation data" (tail of the OpenRouter sorted list, e.g. glm-5-turbo #419/421) to 0.x scores =
 *  "never evaluated" treated as "weakest". Now index reads benchmarks first; rank mode drops models without benchmarks data
 *  (not entering the map -> lookup naturally falls back to the bundled snapshot/curated tiers, unknown != weakest)]
 */
export function parseOpenRouterModels(json: unknown): ParsedSource {
  const arr = Array.isArray((json as any)?.data) ? (json as any).data : Array.isArray(json) ? json : []
  let versionHint: string | null = null
  let maxCreated: number | null = null
  const indexed: Array<{ key: string; entry: CapabilityEntry; created: number | null }> = []
  arr.forEach((m: any, i: number) => {
    const rawName = String(m?.id ?? m?.name ?? "")
    const key = normalizeModelKey(rawName)
    const aa = m?.benchmarks && typeof m.benchmarks === "object" ? m.benchmarks.artificial_analysis : undefined
    const intelligence = firstIndex(num(m?.intelligence), num(aa?.intelligence_index))
    const coding = firstIndex(num(m?.coding), num(aa?.coding_index))
    const agentic = firstIndex(num(m?.agentic), num(aa?.agentic_index))
    const score = firstIndex(intelligence, coding, agentic)
    const created = num(m?.created)
    if (created !== null && (maxCreated === null || created > maxCreated)) maxCreated = created
    if (!key || score === null) return
    indexed.push({ key, entry: { score, intelligence, coding, agentic }, created })
  })
  const models: Record<string, CapabilityEntry> = {}
  if (indexed.length > 0) {
    for (const { key, entry } of indexed) {
      if (!(key in models)) models[key] = entry
    }
    return { models, versionHint: maxCreated !== null ? String(maxCreated) : null, scoreKind: "index" }
  }
  // Rank percentile scores go only to models that truly have evaluation data: missing/empty benchmarks = no evaluation signal at all;
  // their tail-of-list position is a data gap, not a strength order -- drop them (fall back to bundled tiers) to avoid glm-5-turbo-style 0.x artifacts.
  const rankable = arr.filter((m: any) => m?.benchmarks != null && typeof m.benchmarks === "object" && Object.keys(m.benchmarks).length > 0)
  const n = rankable.length
  rankable.forEach((m: any, i: number) => {
    const key = normalizeModelKey(String(m?.id ?? m?.name ?? ""))
    if (!key || key in models) return
    // Rank percentile score: first place 100 -> last place 0 linear (paired with quantile thresholds p80/p60/p40 = top20% S / next20% A / next20% B / rest C)
    const score = n > 1 ? Math.round((1 - i / (n - 1)) * 1000) / 10 : 100
    models[key] = { score }
  })
  return { models, versionHint: maxCreated !== null ? String(maxCreated) : null, scoreKind: "rank" }
}

// ---- cache layer (memory + capability.json; keyed by dir to keep test sandboxes isolated; last-good is never discarded on expiry) ----

let mem: { dir: string; idx: CapabilityIndex | null } | null = null

function validIndex(v: unknown): v is CapabilityIndex {
  const o = v as CapabilityIndex
  return Boolean(
    o && typeof o === "object" &&
    (o.source === "artificial-analysis" || o.source === "openrouter") &&
    typeof o.fetched_at === "number" &&
    o.thresholds && typeof o.thresholds.S === "number" &&
    typeof o.thresholds.A === "number" && typeof o.thresholds.B === "number" &&
    o.models && typeof o.models === "object" && !Array.isArray(o.models),
  )
}

/** Test hook: clear the memory cache (re-read disk after external capability.json rewrite) */
export function resetCapabilityCache(): void {
  mem = null
}

export function loadCapability(): CapabilityIndex | null {
  const dir = paths().dir
  if (mem?.dir === dir) return mem.idx
  const disk = readJson<CapabilityIndex>(paths().capability)
  mem = { dir, idx: validIndex(disk) ? disk : null }
  return mem.idx
}

export function capabilityStale(): boolean {
  const idx = loadCapability()
  return !idx || Date.now() / 1000 - idx.fetched_at >= CAPABILITY_TTL
}

// [2026-08-31]-[bundled default rank snapshot: generated by gen:capability (official ranks frozen, iterated manually per release);
//  enabled as fallback only when the live cache (capability.json) is missing/invalid -- offline fresh installs still get usable ranks]
let bundledCache: CapabilityIndex | null | undefined

export function loadBundledCapability(): CapabilityIndex | null {
  if (bundledCache !== undefined) return bundledCache
  const v = bundledDefaultJson as unknown as CapabilityIndex
  bundledCache = validIndex(v) ? { ...v, bundled: true } : null
  if (bundledCache === null) appendStatusLog("bundled capability rank snapshot corrupted (skipping, falling back to the curated table)")
  return bundledCache
}

/** Pure match against a given capability index, so generation time can reuse the bundled snapshot without reading runtime state. */
export function baseScoreFromCapabilityIndex(modelId: string, idx: CapabilityIndex | null): DynamicBaseResult | null {
  if (!idx) return null
  const norm = normalizeModelKey(modelId)
  const hit = norm ? apiMatch(idx, norm) : null
  if (!hit) return null
  const tier = tierOfScore(hit.entry.score, idx.thresholds)
  return { score: TIER_SCORE[tier], rawScore: hit.entry.score, tier, source: idx.bundled ? "bundled" : "api", version: idx.version, matchedAs: hit.matchedAs }
}

// ---- fetch layer (AA -> OR chained fallback; on failure keep last-good; whole chain fail-open, never throws) ----

async function fetchJson(
  url: string, headers: Record<string, string>,
): Promise<{ json: unknown; etag: string | null }> {
  const res = await fetch(url, {
    headers: { Accept: "application/json", "User-Agent": "opencode-switchman/0.1", ...headers },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return { json: await res.json(), etag: res.headers.get("etag") ?? res.headers.get("x-data-version") }
}

function deriveVersion(prefix: string, etag: string | null, hint: string | null): string {
  if (etag) return etag.replace(/^"|"$/g, "").slice(0, 64) || `${prefix}-${hint ?? ""}`
  return `${prefix}-${hint ?? new Date().toISOString().slice(0, 10)}`
}

/**
 * Refresh the capability index cache (scheduled alongside probes; skipped via the capabilityStale gate within TTL 24h).
 * Success -> memory+capability.json (source/version/fetched_at for decision-log traceability);
 * failure (offline/429/empty parse) -> keep last-good and log it, never throws.
 */
export async function refreshCapability(opts: CapabilityOptions): Promise<void> {
  try {
    const apiKey = opts.apiKey ?? process.env.ARTIFICIAL_ANALYSIS_API_KEY ?? process.env.AA_API_KEY
    const source = opts.source ?? "auto"
    const wantAa = source === "artificial-analysis" || (source === "auto" && Boolean(apiKey))
    const wantOr = source === "openrouter" || source === "auto"
    let parsed: ParsedSource | null = null
    let used: CapabilitySourceName | null = null
    let version: string | null = null
    if (wantAa && apiKey) {
      try {
        const r = await fetchJson(`${AA_BASE}/data/llms/models`, { "x-api-key": apiKey })
        parsed = parseAaModels(r.json)
        used = "artificial-analysis"
        version = deriveVersion("aa", r.etag, parsed.versionHint)
      } catch (exc) {
        appendStatusLog(`capability index primary source AA failed (${exc})${wantOr ? " -> switching to backup source OpenRouter" : " -> keeping last-good/bundled default ranks"}`)
      }
    }
    if (!parsed && wantOr) {
      try {
        const orHeaders: Record<string, string> = {}
        if (!apiKey && process.env.OPENROUTER_API_KEY) orHeaders.Authorization = `Bearer ${process.env.OPENROUTER_API_KEY}`
        const r = await fetchJson(`${OR_BASE}/models?sort=coding-high-to-low`, orHeaders)
        parsed = parseOpenRouterModels(r.json)
        used = "openrouter"
        version = deriveVersion("or", r.etag, parsed.versionHint)
      } catch (exc) {
        appendStatusLog(`capability index backup source OpenRouter failed (${exc}) -> keeping last-good/bundled default ranks`)
      }
    }
    if (!parsed || !used || Object.keys(parsed.models).length === 0) {
      // [2026-08-31]-[log empty parses: a silent return makes upstream believe the refresh succeeded (hit in smoke testing)]
      appendStatusLog(`capability index parsed empty (${used ?? "no source"}) -> keeping last-good/bundled default ranks`)
      return
    }
    const scores = Object.values(parsed.models).map((e) => e.score)
    // rank-derived scores don't match the absolute threshold calibration 62/55/45: force quantile mapping when thresholds are not explicitly configured
    const spec = parsed.scoreKind === "rank" && opts.tierThresholds === undefined ? "quantile" : opts.tierThresholds
    const idx: CapabilityIndex = {
      source: used,
      version,
      fetched_at: Date.now() / 1000,
      thresholds: resolveThresholds(spec, scores),
      models: parsed.models,
      score_kind: parsed.scoreKind,
      counts: { models: scores.length },
    }
    mem = { dir: paths().dir, idx }
    writeJsonAtomic(paths().capability, idx)
    appendStatusLog(`capability index refreshed: ${used} ${scores.length} models (version=${version})`)
    if (opts.lmarenaCheck) crossCheckLmarena(idx).catch(() => {})
  } catch (exc) {
    appendStatusLog(`capability index refresh fail-open (keeping last-good/bundled default ranks): ${exc}`)
  }
}

/** LMArena (api.wulong.dev) optional cross-check: tier-order vs ELO-order agreement, log-only warning, does not affect scoring */
export async function crossCheckLmarena(idx: CapabilityIndex): Promise<void> {
  try {
    const r = await fetchJson(LMARENA_URL, {})
    const body = r.json as any
    const arr = Array.isArray(body) ? body
      : Array.isArray(body?.data) ? body.data
        : Array.isArray(body?.leaderboard) ? body.leaderboard
          : Array.isArray(body?.models) ? body.models : []
    const elo: Record<string, number> = {}
    for (const e of arr) {
      const name = e?.model ?? e?.model_name ?? e?.name
      const v = num(e?.elo ?? e?.score ?? e?.rating ?? e?.arena_elo)
      const key = normalizeModelKey(String(name ?? ""))
      if (key && v !== null) elo[key] = v
    }
    const both = Object.keys(idx.models).filter((k) => k in elo)
    if (both.length < 2) return
    const scores = Object.entries(idx.models)
    let agree = 0
    let pairs = 0
    for (let i = 0; i < scores.length; i++) {
      for (let j = i + 1; j < scores.length; j++) {
        const [ka, ea] = scores[i]!
        const [kb, eb] = scores[j]!
        if (!(ka in elo) || !(kb in elo)) continue
        pairs++
        if (Math.sign(ea.score - eb.score) === Math.sign(elo[ka]! - elo[kb]!)) agree++
      }
    }
    const rate = pairs > 0 ? (agree / pairs) * 100 : 0
    if (rate < 70) {
      appendStatusLog(`capability LMArena cross-check: tier-order vs ELO-order agreement only ${rate.toFixed(0)}% (${both.length} overlapping models) -- data source may be anomalous, manual review advised`)
    }
  } catch (exc) {
    appendStatusLog(`capability LMArena cross-check fail-open (skipped): ${exc}`)
  }
}

// ---- scoring integration layer (sole call site: scoreShell; api hit -> curated table fallback) ----

function apiMatch(idx: CapabilityIndex, normKey: string): { entry: CapabilityEntry; matchedAs: string } | null {
  const exact = idx.models[normKey]
  if (exact) return { entry: exact, matchedAs: normKey }
  let best: { k: string; len: number } | null = null
  for (const k of Object.keys(idx.models)) {
    if (normKey.startsWith(k) && k.length >= MIN_PREFIX_LEN && (!best || k.length > best.len)) best = { k, len: k.length }
  }
  if (best) return { entry: idx.models[best.k]!, matchedAs: best.k }
  return null
}

/**
 * Dynamic base four-level fallback chain: manual ranks (capability-rank.json) -> live api (capability.json) ->
 * bundled default ranks (bundled snapshot) -> curated table.
 * On api/bundled hit score=TIER_SCORE[tierOfScore(index)] (same calibration as curated, tier group order unchanged);
 * on manual hit score=linear rank percentile, tier derived from quantile thresholds (same rank semantics);
 * version is exposed with the data version for routing-decisions.jsonl traceability (bundled-/manual- prefix = override layer source).
 */
export function baseScoreDynamic(modelId: string): DynamicBaseResult {
  const manual = manualRankResult(modelId)
  if (manual) return manual
  const idx = loadCapability() ?? loadBundledCapability()
  const fromIndex = baseScoreFromCapabilityIndex(modelId, idx)
  if (fromIndex) return fromIndex
  const fb = baseScore(modelId)
  return { ...fb, version: null }
}

// ---- manual capability rank override layer (shared by the /modelRank command and hand-edited capability-rank.json) ----

/** [2026-09-03 review-P1-1 fix]-[lane=rank ladder: for n<=4 assign S/A/B/C in order (eliminates tier jumps caused by
 *  quantile degeneration on small n, e.g. a 2-item rank runner-up landing in C); for n>=5 keep the quantile calibration
 *  (top20% S / next20% A / next20% B / rest C, same semantics as the OpenRouter rank order).
 *  rawScore is always the linear rank percentile (fine-grained ordering within a tier unchanged).
 *  The rank->tier table depends only on total, memoized by n (not by file object identity)] */
const manualTierTables = new Map<number, Tier[]>()

function manualTierAt(index: number, total: number): Tier {
  let table = manualTierTables.get(total)
  if (!table) {
    const scores = Array.from({ length: total }, (_, i) => manualLinearScore(i, total))
    const th = resolveThresholds("quantile", scores)
    table = total >= 5
      ? scores.map((s) => tierOfScore(s, th))
      : ["S", "A", "B", "C"]
    manualTierTables.set(total, table)
  }
  return table[Math.min(index, total - 1)]!
}

function manualLinearScore(index: number, total: number): number {
  return total > 1 ? Math.round((1 - index / (total - 1)) * 1000) / 10 : 100
}

function manualRankMatch(normKey: string): { rank: NonNullable<ReturnType<typeof loadCapabilityRank>>; index: number } | null {
  const rank = loadCapabilityRank()
  if (!rank || rank.models.length === 0) return null
  const exact = rank.models.indexOf(normKey)
  if (exact >= 0) return { rank, index: exact }
  // Longest prefix (>=MIN_PREFIX_LEN to avoid false hits): rank entries cover their variants (e.g. gpt-5.6 covers gpt-5.6-luna), same calibration as the curated table
  let best = -1
  let bestLen = 0
  for (let i = 0; i < rank.models.length; i++) {
    const k = rank.models[i]!
    if (k.length >= MIN_PREFIX_LEN && normKey.startsWith(k) && k.length > bestLen) {
      best = i
      bestLen = k.length
    }
  }
  return best >= 0 ? { rank, index: best } : null
}

/** Manual rank hit -> DynamicBaseResult (source="manual"; miss=null, falls through the original fallback chain) */
export function manualRankResult(modelId: string): DynamicBaseResult | null {
  const norm = normalizeModelKey(modelId)
  if (!norm) return null
  const hit = manualRankMatch(norm)
  if (!hit) return null
  const tier = manualTierAt(hit.index, hit.rank.models.length)
  return {
    score: TIER_SCORE[tier],
    rawScore: manualLinearScore(hit.index, hit.rank.models.length),
    tier,
    source: "manual",
    version: `manual-${hit.rank.updated_at || "unset"}`,
    matchedAs: hit.rank.models[hit.index]!,
  }
}
