// [2026-09-04]-[English localization: translate comments; no logic change]
// Six-lane base chain policy: membership and order are both generated by the capability-score × lane-affinity ×
// structural-gate algorithm.
// Runtime computeLane further layers health, breaker, watermark and live-cost ordering; this module only produces the
// candidate baseline.
// [2026-08-31]-[de-vendorization: removed the DS chain-tail / last-seat reservation (pool-name rules abolished); scores
//  multiply billingBoost×unknownPenalty, so api billing and unknown groups sink naturally via the factors; factors are
//  injected via LaneFactorResolvers (generation time = factory config, runtime = user jsonc)]
import type { Lane } from "./types"
import { LANE_ORDER } from "./types"
import { CAPABILITY_LEVEL_RANK, TIER_RANK, UNKNOWN_PENALTY, capabilityLevelOf } from "./model-ranks"
import type { CapabilityLevel, Tier } from "./model-ranks"

export interface LaneShellAttr {
  effort: string
  capability: string
  vision: boolean
  pool: string
  modelId?: string
  cost?: number | null
}

/** Capability-score result (tier is the grouping/ordering primary key; shape shared with capability.DynamicBaseResult) */
export interface CapabilityScore { score: number; tier: Tier | null; rawScore?: number; source?: string }

export interface LanePolicyInput {
  /** [deprecated · not read by the algorithm] Legacy call-shape compatibility; candidates are no longer decided by
   *  this static list (neither computeLaneChain nor laneBaseChain references it).
   *  [2026-09-02]-[re-review P1: selectInjectableDefs passes [] — if the algorithm ever reads builtin again, static
   *  lanes would be silently dropped here] */
  builtin: readonly string[]
  activeShells: ReadonlySet<string>
  shells: ReadonlyMap<string, LaneShellAttr>
  /** Max candidate chain length (default 4) */
  maxLen?: number
  capabilityOf?: (modelId: string) => number | CapabilityScore
  /** [2026-08-31]-[de-vendorization: billing/unknown-group factor resolvers (default = the all-1.0 subscription known-model baseline)] */
  billingBoostOf?: (provider: string) => number
  unknownOf?: (modelId: string) => boolean
  /** [2026-09-02]-[favorites first: favorite models (by modelId) sort first within the same tier; tiers never invert (capability levels are irreversible)] */
  preferredModels?: ReadonlySet<string>
}

// [2026-08-29]-[scoring-engine reuse: LANE_SPEC ordinals exported for scoring.effortFit to compute lane affinity]-
// [2026-09-02]-[thinking-level preference layer: efforts keeps only the thinking-level preference order
//  (hard/review default high→xhigh→max, main/mechanical/vision default medium→high→xhigh→max, economy default
//  low→medium→high); off no longer enters any lane preference order — off shells are always lane-level fallback
//  (when the lane has thinking-level candidates they rank after all thinking levels, see the computeLaneChain
//  thinking-level partition), serving only models that support just on/off or scenarios where other levels are unavailable]
export const LANE_SPEC: Record<Lane, { efforts: string[]; vision: boolean; ro: boolean; minimumLevel: CapabilityLevel | null }> = {
  economy: { efforts: ["low", "minimal", "medium", "high"], vision: false, ro: false, minimumLevel: "L1" },
  mechanical: { efforts: ["medium", "high", "xhigh", "max"], vision: false, ro: false, minimumLevel: "L2" },
  main: { efforts: ["medium", "high", "xhigh", "max"], vision: false, ro: false, minimumLevel: "L3" },
  hard: { efforts: ["high", "xhigh", "max", "medium"], vision: false, ro: false, minimumLevel: "L4" },
  vision: { efforts: ["medium", "high", "xhigh", "max"], vision: true, ro: false, minimumLevel: null },
  // [2026-09-05]-[review same-family fallback: cross-family is a preference, not a hard gate — cross-family candidates
  //  rank first on the chain and a same-family ro shell is a last-resort DOWNGRADED self-review seat (see buildPartition
  //  and scoring.rankCandidates); the ro hard gate is unchanged]
  // Review prefers S(L5); A(L4) can only serve as a top-2 fill-in candidate and must still pass the ro hard gate.
  review: { efforts: ["high", "xhigh", "max", "medium"], vision: false, ro: true, minimumLevel: "L5" },
}

export function capabilityLevelFor(capability: number | CapabilityScore): CapabilityLevel {
  // Numeric callbacks are the legacy compatibility form for old tests/external calls; without source and tier they keep the original non-filtering semantics.
  if (typeof capability === "number" || !capability.tier) return "L5"
  return capabilityLevelOf(capability.tier, capability.source)
}

export function meetsLaneCapability(lane: Lane, capability: number | CapabilityScore): boolean {
  const minimum = LANE_SPEC[lane]?.minimumLevel
  return minimum === null || CAPABILITY_LEVEL_RANK[capabilityLevelFor(capability)] >= CAPABILITY_LEVEL_RANK[minimum]
}

/** Same-level models are the regular candidates; [2026-09-02] vision only does vision-pool filtering and takes part in no lane scoring. */
export function isPrimaryCandidate(lane: Lane, capability: number | CapabilityScore): boolean {
  // Legacy numeric callbacks carry no level info; keep fail-open so external legacy calls are not misjudged as having no same-level candidate.
  if (typeof capability === "number") return true
  const target = LANE_SPEC[lane]?.minimumLevel
  return target === null || capabilityLevelFor(capability) === target
}

/**
 * Cross-level fallback when all same-level candidates are unavailable. Prefers one level higher; when main/hard/review
 * have no higher option, an adjacent lower-level known model may be used. L1 is the unknown-model floor and cannot take
 * text tasks upward.
 */
export function isFallbackCandidate(lane: Lane, capability: number | CapabilityScore): boolean {
  if (typeof capability === "number" || !capability.tier || capability.source === "global") return false
  const target = LANE_SPEC[lane]?.minimumLevel
  if (target === null) return false
  const level = capabilityLevelFor(capability)
  const delta = CAPABILITY_LEVEL_RANK[level] - CAPABILITY_LEVEL_RANK[target]
  if (delta > 0) return true
  return (lane === "main" && level === "L2") ||
    (lane === "hard" && level === "L3") ||
    (lane === "review" && level === "L4")
}

/** Legacy call-name compatibility: one-level-lower fill-in is still limited to main/hard/review. */
export function isPromotionCandidate(lane: Lane, capability: number | CapabilityScore): boolean {
  if (typeof capability === "number" || !capability.tier || capability.source === "global") return false
  const level = capabilityLevelFor(capability)
  return (lane === "main" && level === "L2") ||
    (lane === "hard" && level === "L3") ||
    (lane === "review" && level === "L4")
}

export function laneCandidateLimit(lane: Lane): number {
  return lane === "main" || lane === "hard" || lane === "review" ? 6 : 4
}

export interface LaneAlgorithmShell extends LaneShellAttr { name: string; modelId: string; provider?: string }

/** Billing/unknown-group factor resolvers (fallback baseline when billingBoostOf/unknownOf are absent) */
export interface LaneFactorResolvers {
  billingBoostOf?: (provider: string) => number
  unknownOf?: (modelId: string) => boolean
}

/**
 * Candidate algorithm shared by generation time and runtime: structural gates → per-model preferred face → tier
 * grouping (capability levels never invert) → within-group capability×affinity×billing×unknown product score →
 * cost/name tiebreak.
 * [2026-08-31]-[final-review P0-1: the tier-grouping primary key shares one source with rankCandidates — an api-billed
 *  S tier (0.85) must not be overtaken within the same tier by an A-tier subscription model (0.85) via cost/name;
 *  unknownPenalty only sinks to bottom within the same tier, never squeezes candidates across tiers]
 * The effort penalty keeps the legacy filler's "each ordinal +1" baseline, converted to a product factor via 1/(1+penalty).
 * [2026-09-02]-[removed the vision penalty: the capability score (coding/intelligence indices) already measures text
 *  ability fully; vision is an orthogonal modality attribute, so ÷2 for vision shells in text lanes was double pricing;
 *  the vision flag now only serves to filter non-vision models out of the vision pool (see the filter below and the
 *  gates hard gate) and no longer takes part in text-lane scoring]-
 * [2026-09-02]-[thinking-level partition: off shells = lane-level fallback. Candidates are first partitioned by whether
 *  effort is off; each partition independently runs the same-level-first / cross-level fallback algorithm; the chain =
 *  thinking partition first, off partition last (off absorbs only the remaining seats) — when the lane has thinking-level
 *  candidates, off shells no longer occupy the chain head ("thinking vs not thinking differs a lot; off is fallback only")]
 */
export function computeLaneChain(shells: readonly LaneAlgorithmShell[], capabilityOf: (modelId: string) => number | CapabilityScore, lane: Lane, resolvers: LaneFactorResolvers = {}, preferredModels?: ReadonlySet<string>): string[] {
  const spec = LANE_SPEC[lane] ?? LANE_SPEC.main
  // [2026-09-02]-[favorites first: user favorite models sort first within the same tier; the off fallback partition still sinks to bottom as a whole (quality floor unchanged)]
  const preferredOf = (modelId: string): number => (preferredModels?.has(modelId) ? 0 : 1)
  // [2026-09-02]-[ro/rw pool split: review picks only from the ro pool, all other lanes only from the rw pool
  //  (split pools first, then prefer within pool); cross-pool fallback only when the own pool is empty (fail-open; an
  //  rw task landing on an ro shell is still blocked by the gates). Previously the same model's ro/rw faces mixed into
  //  one ordering pool, and fallback seats had no rawScore tiebreak, so 5.3-high(rw) was sliced out of the hard chain
  //  by lexicographic 52<53 → the injection face lost the rw variant and the hard banner could only land on an ro shell]
  //  -[impact: ro shells no longer appear on non-review chains; the two faces of one model enter per-lane faces by need]
  const facePool = shells.filter((s) => (spec.ro ? s.capability === "ro" : s.capability !== "ro"))
  const pool = facePool.length > 0 ? facePool : shells.filter((s) => (spec.ro ? s.capability !== "ro" : s.capability === "ro"))
  const ranked = pool
    .map((shell) => {
      const effort = spec.efforts.indexOf(shell.effort)
      const offFallback = shell.effort === "off" ? 1 : 0
      const effortPenalty = effort < 0 ? spec.efforts.length : effort
      const billingBoost = resolvers.billingBoostOf && shell.provider !== undefined ? resolvers.billingBoostOf(shell.provider) : 1.0
      const unknownPenalty = resolvers.unknownOf?.(shell.modelId) ? UNKNOWN_PENALTY : 1.0
      const cap = capabilityOf(shell.modelId)
      const capScore = typeof cap === "number" ? cap : cap.score
      const tierRank = typeof cap === "number" ? 0 : (cap.tier ? TIER_RANK[cap.tier] : 0)
        return {
        shell,
        capability: cap,
        level: capabilityLevelFor(cap),
        offFallback,
        preferred: preferredOf(shell.modelId),
        score: capScore / (1 + effortPenalty) * billingBoost * unknownPenalty,
        tierRank,
        rawScore: typeof cap === "number" ? undefined : cap.rawScore,
      }
    })
    .filter(({ shell }) => !spec.vision || shell.vision)
  // One lane/face per model: regular lanes prefer rw, review prefers ro; off yields to thinking levels; the other face
  // is allowed as fallback only when no preferred face exists.
  const preferred = spec.ro ? "ro" : "rw"
  ranked.sort((a, b) => Number(a.shell.capability !== preferred) - Number(b.shell.capability !== preferred) || a.offFallback - b.offFallback || a.preferred - b.preferred || b.score - a.score || (typeof a.shell.cost === "number" ? a.shell.cost : Infinity) - (typeof b.shell.cost === "number" ? b.shell.cost : Infinity) || a.shell.name.localeCompare(b.shell.name))
  const onePerModel = new Map<string, typeof ranked[number]>()
  for (const candidate of ranked) if (!onePerModel.has(candidate.shell.modelId)) onePerModel.set(candidate.shell.modelId, candidate)
  const ordered = [...onePerModel.values()]
    .sort((a, b) => {
       if (a.tierRank !== b.tierRank) return a.tierRank - b.tierRank
       if (a.preferred !== b.preferred) return a.preferred - b.preferred
       if (b.score !== a.score) return b.score - a.score
       // tier guarantees no inversion across levels; on a same-tier total-score tie, fall back to the real capability index so S/A/B/C discretization does not degrade into name ordering.
       if (a.rawScore !== undefined || b.rawScore !== undefined) return (b.rawScore ?? -Infinity) - (a.rawScore ?? -Infinity)
      const ac = typeof a.shell.cost === "number" ? a.shell.cost : Number.POSITIVE_INFINITY
      const bc = typeof b.shell.cost === "number" ? b.shell.cost : Number.POSITIVE_INFINITY
      return ac - bc || a.shell.name.localeCompare(b.shell.name)
    })
  // [2026-09-01]-[same-level first: same-level candidates and fallback candidates are kept apart; runtime exhausts the
  //  same level before enabling cross-level entries.]-
  // [2026-09-02]-[thinking-level partition: the off partition independently runs the same same-level/fallback algorithm
  //  and sinks to bottom as a whole, absorbing only the remaining chain seats.]
  const buildPartition = (pool: typeof ordered) => {
    // Fallbacks start from the nearest level, so an S-tier model does not leapfrog L2/L3 straight into economy when L1 is absent.
    const targetRank = spec.minimumLevel === null ? 0 : CAPABILITY_LEVEL_RANK[spec.minimumLevel]
    const primary = pool.filter(({ capability }) => isPrimaryCandidate(lane, capability))
    const fallbacks = pool
      .filter(({ capability }) => isFallbackCandidate(lane, capability))
      .sort((a, b) =>
        Math.abs(CAPABILITY_LEVEL_RANK[a.level] - targetRank) - Math.abs(CAPABILITY_LEVEL_RANK[b.level] - targetRank) ||
        a.tierRank - b.tierRank || a.preferred - b.preferred || b.score - a.score ||
        // [2026-09-02]-[fallback seats gain a rawScore tiebreak: score had already degenerated to a constant 1.0 within
        //  the same level, and without this key lexicographic order would slice stronger models (53>52) out of the top-2
        //  fallback seats]-[impact: cross-level fallback prefers the real capability index, same source as the ordered main ordering]
        (b.rawScore ?? -Infinity) - (a.rawScore ?? -Infinity) || a.shell.name.localeCompare(b.shell.name))
    // [2026-09-05]-[review last-resort seats: when no S(L5) primary and no A(L4) fallback candidate exists (e.g. all
    //  pools except B-tier models are alive), the review partition would go empty → the TUI sidebar showed
    //  "review: none available" and every reviewer dispatch was denied. Take the best 2 shells of the (already
    //  tier/score-ordered) pool instead so the chain is never empty while any ro shell exists; same-family seats rank
    //  last at runtime and the dispatch declares DOWNGRADED. Other lanes unchanged (empty = terminal failure protocol).]
    if (lane === "review" && primary.length === 0 && fallbacks.length === 0) return pool.slice(0, 2)
    return [...primary.slice(0, 4), ...fallbacks.slice(0, 2)]
  }
  const thinking = ordered.filter(({ shell }) => shell.effort !== "off")
  const offOnly = ordered.filter(({ shell }) => shell.effort === "off")
  return [...buildPartition(thinking), ...buildPartition(offOnly)].map(({ shell }) => shell.name)
}

/** Activation-face candidate chain: ignores stale static lanes and reruns the same algorithm over the current full shell set. */
export function laneBaseChain(lane: Lane, input: LanePolicyInput): string[] {
  const candidates: LaneAlgorithmShell[] = []
  for (const name of input.activeShells) {
    const attr = input.shells.get(name)
    if (!attr) continue
    candidates.push({ name, ...attr, modelId: attr.modelId ?? name })
  }
  const resolvers: LaneFactorResolvers = { billingBoostOf: input.billingBoostOf, unknownOf: input.unknownOf }
  return computeLaneChain(candidates, input.capabilityOf ?? (() => 1), lane, resolvers, input.preferredModels).slice(0, input.maxLen ?? laneCandidateLimit(lane))
}

/** All six lanes' base chains (assembled once for the banner) */
export function laneBaseChains(input: Omit<LanePolicyInput, "builtin">, builtinLanes: Record<string, readonly string[]>): Record<Lane, string[]> {
  const out = {} as Record<Lane, string[]>
  for (const lane of LANE_ORDER) {
    out[lane] = laneBaseChain(lane, { ...input, builtin: builtinLanes[lane] ?? [] })
  }
  return out
}
